# Volume for Ding, Dong
#Volume: From 0.0 to 1
volume: 0.5
#Led Control Respeaker
#No Respeaker:0, #Respeaker 2 Mic Hat/Respeaker 4 Mic Array : 1, Respeaker USB Mic Array 2.0: 2, RespeakerCoreV2: 3
re_speaker: 2
#Led Respeaker for Pi
#Tốc độ nháy đèn
led_do: 15
led_xanh: 14
# Wakeup_Engine
wakeup_engine: 1
# 1: PicoVoice
#PicoVoice
sensitivities:
 - 0.3
 - 0.3
keyword_paths:
 - hey google_raspberry-pi.ppn 
 - ok google_raspberry-pi.ppn
keywords:
 - hey google 
 - ok google
